# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HUFV9I8o6OKncgIYdJ0__NqwSnxcG8R6
"""

import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.utils._testing import ignore_warnings
from sklearn.exceptions import ConvergenceWarning
import warnings
warnings.filterwarnings('ignore')


# ----------------------------------------------------------
# 운명의 길 한국어 매핑
# ----------------------------------------------------------
PATH_KO = {
    'Nihility'     : '공허',
    'Destruction'  : '파멸',
    'Hunt'         : '수렵',
    'Erudition'    : '지식',
    'Harmony'      : '화합',
    'Abundance'    : '풍요',
    'Preservation' : '보존',
    'Remembrance'  : '기억',
    'Elation'      : '환락',
}

FEATURE_KO = {
    'atk_base'   : '공격력',
    'def_base'   : '방어력',
    'hp_base'    : 'HP',
    'base_spd'   : '속도',
    'base_aggro' : '어그로 수치',
    'max_energy' : '최대 에너지',
}

# ----------------------------------------------------------
# 데이터셋 로드
# ----------------------------------------------------------

chars = pd.read_csv("characters.csv")
stats = pd.read_csv("character_stats.csv")

stats_max = stats[stats['ascension'] == 6].copy()
df = chars.merge(stats_max, on='character_id')
df['path_ko'] = df['path'].map(PATH_KO)

print(f"총 캐릭터 수 : {len(df)}명")
print(f"운명의 길    : {' / '.join(PATH_KO[p] for p in sorted(PATH_KO))}")
print()

# ----------------------------------------------------------
# 피처 & 타겟 정의
# ----------------------------------------------------------
features = list(FEATURE_KO.keys())

X = df[features].fillna(df[features].median())
y = df['path_ko']

print("[ 사용 피처 ]")
for eng, ko in FEATURE_KO.items():
    print(f"  - {ko} ({eng})")

print(f"\n[ 운명의 길별 캐릭터 수 ]")
for path, cnt in y.value_counts().items():
    print(f"  {path:6s} : {cnt}명")
print()

# ----------------------------------------------------------
# 학습 / 테스트 데이터 분리 (80:20)
# ----------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ----------------------------------------------------------
# 모델 학습
# ----------------------------------------------------------

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)


svm = SVC(kernel='rbf', C=10, gamma='scale', random_state=42)
svm.fit(X_train_scaled, y_train)


# ----------------------------------------------------------
# 게임 밸런스
# ----------------------------------------------------------
y_pred_clf = clf.predict(X_test)
y_pred_svm = svm.predict(X_test_scaled)
acc_clf    = accuracy_score(y_test, y_pred_clf)
acc_svm    = accuracy_score(y_test, y_pred_svm)
best_acc  = max(acc_clf, acc_svm)
best_pred = y_pred_clf if acc_clf >= acc_svm else y_pred_svm
best_acc  = max(acc_clf, acc_svm)
best_name = "분류 모델" if acc_clf >= acc_svm else "보조 모델"

print()
print("=" * 60)
print("게임 밸런스")
print("=" * 60)
print()
print(f"  정확도 {best_acc*100:.1f}% : 스탯만으로 운명의 길을 분류한 결과")

print("  [ 오분류 캐릭터 목록 ]")
result_df = pd.DataFrame({
    '캐릭터'    : df.loc[X_test.index, 'character_name'].values,
    '실제 운명' : y_test.values,
    '예측 운명' : best_pred,
})
wrong = result_df[result_df['실제 운명'] != result_df['예측 운명']]
if len(wrong) > 0:
    for _, row in wrong.iterrows():
        print(f"  ✗ {row['캐릭터']:25s}  실제: {row['실제 운명']:4s} → 예측: {row['예측 운명']}")
else:
    print("모든 테스트 샘플이 정확히 분류되었습니다.")

importances = clf.feature_importances_
feat_df = pd.DataFrame({
    '피처'  : [FEATURE_KO[f] for f in features],
    '중요도' : importances
}).sort_values('중요도', ascending=False)

print()
print("  [ 스탯 기여도 순위 ]")
for _, row in feat_df.iterrows():
    bar = "█" * int(row['중요도'] * 40)
    print(f"  {row['피처']:10s}  {bar} {row['중요도']:.4f}")

print("=" * 60)
print("예측 및 정확도")
print("=" * 60)

print(f"  [분류 모델]  정확도 : {acc_clf:.4f}  ({acc_clf*100:.1f}%)")
print(f"  [보조 모델]  정확도 : {acc_svm:.4f}  ({acc_svm*100:.1f}%)")
print()


print(f"  ★ 최종 채택 : {best_name} (정확도 {best_acc*100:.1f}%)")
print()

print("[ 운명의 길별 상세 분류 결과 ]")
print(classification_report(y_test, y_pred_clf,
                             labels=sorted(PATH_KO.values()),
                             zero_division=0))

# ----------------------------------------------------------
# 8. 랜덤 캐릭터 예측 테스트
# ----------------------------------------------------------
print()
print("=" * 60)
print("랜덤 캐릭터 예측 테스트")
print("=" * 60)
print("  학습에 사용한 전체 데이터에서 캐릭터를 무작위로 뽑아")
print("  스탯만 보고 운명의 길을 맞히는지 확인합니다.")
print()

# 50명 무작위 추출
sample_indices = random.sample(range(len(df)), 50)
correct = 0

for i, idx in enumerate(sample_indices, 1):
    row         = df.iloc[idx]
    name        = row['character_name']
    actual_path = row['path_ko']
    stat_input  = pd.DataFrame([row[features].fillna(df[features].median().iloc[0])])

    predicted_path = clf.predict(stat_input)[0]
    is_correct     = "정답" if predicted_path == actual_path else "오답"
    if predicted_path == actual_path:
        correct += 1

    print(f"  [{i}] {name}")
    print(f"       공격력 {row['atk_base']:.0f}  |  방어력 {row['def_base']:.0f}  |  HP {row['hp_base']:.0f}")
    print(f"       속도 {row['base_spd']:.0f}  |  어그로 {row['base_aggro']:.0f}  |  최대에너지 {row['max_energy']:.0f}")
    print(f"       → 예측: {predicted_path:4s}   실제: {actual_path:4s}   {is_correct}")
    print()

print(f"  랜덤 테스트 결과 : {correct}/{len(sample_indices)} 정답 ({correct/len(sample_indices)*100:.0f}%)")

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler as KNNScaler

# 각 스탯의 실제 min~max 범위 안에서 랜덤 생성
stat_ranges = {
    'atk_base'   : (int(X['atk_base'].min()),   int(X['atk_base'].max())),
    'def_base'   : (int(X['def_base'].min()),   int(X['def_base'].max())),
    'hp_base'    : (int(X['hp_base'].min()),    int(X['hp_base'].max())),
    'base_spd'   : (int(X['base_spd'].min()),   int(X['base_spd'].max())),
    'base_aggro' : (int(X['base_aggro'].min()), int(X['base_aggro'].max())),
    'max_energy' : (int(X['max_energy'].min()), int(X['max_energy'].max())),
}

random_stats = {stat: random.randint(low, high) for stat, (low, high) in stat_ranges.items()}
random_input = pd.DataFrame([random_stats])

# 운명의 길 예측
predicted = clf.predict(random_input)[0]

print()
print("  [ 생성된 랜덤 캐릭터 스탯 ]")
for eng, ko in FEATURE_KO.items():
    print(f"  {ko:8s} : {random_stats[eng]}")
print()
print(f"  ★ 예측된 운명의 길 : {predicted}")
print()

# KNN으로 가장 가까운 캐릭터 10명 탐색
knn_scaler = KNNScaler()
X_knn = knn_scaler.fit_transform(X)
random_knn = knn_scaler.transform(random_input)

knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_knn, y)

distances, indices = knn.kneighbors(random_knn)

print("  [ 스탯이 가장 유사한 캐릭터 TOP 10 ]")
for rank, (dist, idx) in enumerate(zip(distances[0], indices[0]), 1):
    similar = df.iloc[idx]
    print(f"  {rank}위  {similar['character_name']:25s}  운명의 길: {similar['path_ko']:4s}  (유사도 거리: {dist:.2f})")

print()
print("  [ 주변 10명의 운명의 길 분포 ]")
path_counts = {}
for idx in indices[0]:
    path = df.iloc[idx]['path_ko']
    path_counts[path] = path_counts.get(path, 0) + 1

total = sum(path_counts.values())
for path, count in sorted(path_counts.items(), key=lambda x: -x[1]):
    bar        = "█" * count
    ratio      = count / total * 100
    marker     = "  ← 예측 결과" if path == predicted else ""
    print(f"  {path:4s}  {bar:<10s} {count}명  ({ratio:.0f}%){marker}")

predicted_ratio = path_counts.get(predicted, 0) / total * 100
print()
if predicted_ratio >= 50:
    print(f"예측 신뢰도 높음 — 주변 캐릭터의 {predicted_ratio:.0f}%가 {predicted}")
elif predicted_ratio >= 30:
    print(f"예측 신뢰도 보통 — 주변 캐릭터의 {predicted_ratio:.0f}%가 {predicted}, 경계선에 가까운 스탯")
else:
    print(f"예측 신뢰도 낮음 — 주변 캐릭터의 {predicted_ratio:.0f}%만 {predicted}, 스탯만으로 역할 구분 어려움")
